### ISSUE TITLE
Bug: Special Characters cannot be included in job bundles

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud#481]
### Describe the bug

Many non-English speaking users will have special characters like ñ in their filenames. This can cause errors when submitting to Deadline Cloud.

To be clear, special characters can be included in job attachments, but if any strings, like the input scene path or the output path, end up in the template.yaml or template.json file, it will fail to submit.

### Expected Behaviour

We should support any string that can be a valid path.

### Current Behaviour

When you submit a job with invalid characters you get the following error:
![image](https://github.com/user-attachments/assets/1c5dcbc7-b18b-4d18-92f6-449f1f092986)

### Reproduction Steps

Make a job bundle and make either the input scene path or the output path include a special character. Try to submit it through `deadline bundle gui-submit`

### Environment

At minimum:
1. Operating system: Windows
2. Output of `python3 --version`: 3.11.1
3. Output of `deadline --version`: version 0.48.4
4. If this is from a version installed by the Deadline Cloud Submitter installer, then what version of the submitter installer? The version that came out in September.

**Comment by mwiebe** [comment]
From the error message, it looks like it's reading a file that is not encoded as utf-8. If the input was utf-8, I believe it would work, and utf-8 does support all international characters. We could make changes to make that error message a lot friendlier though. This could be due to a text editor mis-configuration.

Can you attach a sample job bundle that produces the error?
